### ISSUE TITLE
Responsive: Pumpkin carving section

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#103]
Need someone to update the punpkin carving section on index.html to be responsive

**Comment by ramyamahi** [comment]
Please assign this to me @lukes-code

**Comment by ramyamahi** [comment]
Please check the PR #104 @lukes-code

**Comment by lukes-code** [comment]
> Please check the PR #104 @lukes-code

Looks good. Good job!
