### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by IsaacArnold** [lukes-code/Hacktoberfest-Spooks#105]
Hey Luke - I've just noticed there is no README file for this project. Am I able to work on this? 

I'm having trouble making the game page responsive and fixing the width, so I would like to contribute in another way by adding a README file. 

Is this ok? If so, can you please unassign me from the responsive issue and assign me to this issue?

Thanks!

**Comment by lukes-code** [comment]
> Hey Luke - I've just noticed there is no README file for this project. Am I able to work on this? 
> 
> I'm having trouble making the game page responsive and fixing the width, so I would like to contribute in another way by adding a README file. 
> 
> Is this ok? If so, can you please unassign me from the responsive issue and assign me to this issue?
> 
> Thanks!

Can you change the name of the contributions file to read me and add more details that? Also, can you raise the issue and I'll assign
