### ISSUE TITLE
Change CONTRIBUTING to README

### ISSUE THREAD

**Issue by IsaacArnold** [lukes-code/Hacktoberfest-Spooks#108]
Changing the contributing file to a README file and adding more details in here. 

Will add information such as:
- How to create a PR
- How to raise an issue

Let me know of any other important info you'd like added :)

**Comment by lukes-code** [comment]
Sounds great. Could you also add my Instagram URL and say that people are welcome to ask there for help? Thanks dude

**Comment by IsaacArnold** [comment]
Absolutely I can do that 👍🏼
