### ISSUE TITLE
Add scroll to div to button

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#11]
Need to change the anchor tag on the "Play Game" button in the header so that when it is clicked, it scrolls to the trick or treat section *Tip* Change the anchor tag link to the trick or treat id *Tip*

**Comment by attreyee-muk** [comment]
Hello! Can I work on this issue?

**Comment by lukes-code** [comment]
Absolutely :)

**Comment by amanj752** [comment]
can you pls assign this work to me I can do this?

**Comment by lukes-code** [comment]
Sure, who ever can complete it first will get the pull request

> can you pls assign this work to me I can do this?

**Comment by amanj752** [comment]
I have done with this can you check  it.

**Comment by lukes-code** [comment]
@amanj752 this has now been completed by @a-muk just before you. I have still added the hacktoberfest-accepted label to both so it should still count towards your hacktoberfest. Happy coding both!
