### ISSUE TITLE
Main section

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#2]
Halloween page needs a main section in the page. This can be anything as long as its halloween themed.

**Comment by SleepyAryan** [comment]
can i contribute to it

**Comment by lukes-code** [comment]
> can i contribute to it

Yes, please create a halloween themed section. Just one section in the main body on the page. It can be anything you like as long as its halloween themed. Enjoy!

**Comment by SleepyAryan** [comment]
> > can i contribute to it
> 
> Yes, please create a halloween themed section. Just one section in the main body on the page. It can be anything you like as long as its halloween themed. Enjoy!

as in like a division with halloween themed stuff ??

**Comment by lukes-code** [comment]
> > > can i contribute to it
> > 
> > 
> > Yes, please create a halloween themed section. Just one section in the main body on the page. It can be anything you like as long as its halloween themed. Enjoy!
> 
> as in like a division with halloween themed stuff ??

Exactly!
