### ISSUE TITLE
Navbar Responsive

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#36]
There is a navbar in index.html and contact.html but it is not responsive.
I need someone to make the links in the navbar go in to a dropdown when the window size is tablet/mobile.

**Comment by STM3900** [comment]
asign me, i will do that

**Comment by amanj752** [comment]
Assigne to me, I can do that

**Comment by lukes-code** [comment]
Hi @STM3900 , sorry but that issue was opened with @amanj752 in mind. If you want CSS issues, I can find some more for you if you like?

**Comment by STM3900** [comment]
Oh sorry.
Yeah if you can that would be great!

**Comment by lukes-code** [comment]
> Oh sorry. Yeah if you can that would be great!

Made one for you, comment on it and ill assign

**Comment by amanj752** [comment]
I am done with header can u confirm it

**Comment by amanj752** [comment]
pls accept my pull request so that I get one more label and assign me another issue related to CSS or Responsiveness

**Comment by lukes-code** [comment]
> pls accept my pull request so that I get one more label and assign me another issue related to CSS or Responsiveness

Someone was already assigned this job. I will not make but I will add the hacktoberfest-accepted tag.

**Comment by amanj752** [comment]
heyy can you add hactoberfest-accepted label because due to this lebel only my PR will count because still showing in pending pls add it.
