### ISSUE TITLE
Make Spooky Jokes section responsive

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#37]
Need someone to make the ''Spooky Jokes'' section in the index.html responsive.

**Comment by STM3900** [comment]
Thank you, i will do that

**Comment by lukes-code** [comment]
> Thank you, i will do that

Awesome, have fun!

**Comment by STM3900** [comment]
Done!
How do i link my pull request to this issue ?

**Comment by lukes-code** [comment]
> Done! How do i link my pull request to this issue ?

It's ok ive linked it. I've added the hacktoberfest-accepted too. The hacktoberfest site is a little slow today, wait about 10 minutes and it should appear for you. Happy coding!

**Comment by STM3900** [comment]
thanks à lot ! If you want i can help on other issues in css

**Comment by lukes-code** [comment]
@STM3900  just made a new issue, please comment if you want it :)
