### ISSUE TITLE
Fix trick or treat images

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#39]
If you go to the trick or treat section and click play game you'll notice that 'trick' and 'treat' and jpegs and the background colour is different. Place create new images or replace with text so that it doesn't look like this

**Comment by IsaacArnold** [comment]
Hi Luke - I'd like to work on this one if possible?

**Comment by lukes-code** [comment]
> Hi Luke - I'd like to work on this one if possible?

Go for it!
