### ISSUE TITLE
Semantic footer

### ISSUE THREAD

**Issue by IsaacArnold** [lukes-code/Hacktoberfest-Spooks#46]
Hey Luke! 

I'd like to change the footer HTML tags to be more semantic please. Will I just go ahead and make a pull request for it? Or will you assign the issue to me? 

Cheers!

**Comment by lukes-code** [comment]
Yes, can you do this one as a priority as someone else is working on the footer too?

**Comment by IsaacArnold** [comment]
Sure thing, I'm onto it now :)
