### ISSUE TITLE
Wrapper change

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#51]
Need someone to take the current image that is in the wrapper and make it a full width background image covering all of the nav, and wrapper until the orange section.

**Comment by STM3900** [comment]
👋

**Comment by lukes-code** [comment]
Thanks, have fun! If you have any issues or queries, just sent a comment on here.

**Comment by STM3900** [comment]
Done, tell me if something is wrong

**Comment by lukes-code** [comment]
Looks good to me, submit a pull request if you like

**Comment by STM3900** [comment]
submited
