### ISSUE TITLE
Image fixer for trick or treat game

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#64]
We have changed the images as part of the trick or treat game, but now the game does not work.
The javascript adds a trick class or a treat class. Please change the CSS of these classes so that the file path for the images are correct (check the Images folder for the correct images).

**Comment by amanj752** [comment]
I can do it can you assign me.

**Comment by lukes-code** [comment]
> I can do it can you assign me.

Have fun!

**Comment by soumali28** [comment]
I made the changes but can not commit it.

**Comment by lukes-code** [comment]
> I made the changes but can not commit it.

You must commit to your forked repo, then do a pull request. Please ask next time for the case to be assigned as this issue has now been assigned to @amanj752

**Comment by amanj752** [comment]
I am done with this can you assign me any other issue related to css and responsiveness

**Comment by lukes-code** [comment]
> I am done with this can you assign me any other issue related to css and responsiveness

Keep an eye out for the issues tab, I don't have any new ones yet

**Comment by amanj752** [comment]
heyy can you add hactoberfest-accepted label because due to this  lebel only my PR will count because still showing in pending pls add it.

**Comment by lukes-code** [comment]
> heyy can you add hactoberfest-accepted label because due to this  lebel only my PR will count because still showing in pending pls add it.

It stays pending for 14 days. This is not because of me it is just a hacktoberfest rule

**Comment by amanj752** [comment]
ok
