### ISSUE TITLE
Navbar changes

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#65]
The navbar is overlapping the scroll bar, please remove this.
Also need to add smooth scrolling to the css so when the user clicks on the links in the navbar it scrolls smoothly instead of jumping straight to the section.

Please ask for this case to be assigned before completing the work.

**Comment by shaheerk1** [comment]
Hey, can I work on this issue ?

**Comment by lukes-code** [comment]
> Hey, can I work on this issue ?

Sure!

**Comment by shaheerk1** [comment]
Ok, I'll start it now

**Comment by shaheerk1** [comment]
I have made a pull request fixing this issue can you check it.

**Comment by lukes-code** [comment]
> I have made a pull request fixing this issue can you check it.

Checked and responded. Good work so far.

**Comment by shaheerk1** [comment]
It was great working on this.
