### ISSUE TITLE
Add styling to the joke section

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#66]
The Spooky Jokes section works fine, however it looks a big basic. Please add some styling to the orange box to make this section look more appealing. (For example, the flowers on either side in the footer makes that section look great)

Please ask for this case to be assigned before completing the work.

**Comment by sheharyarIshfaq** [comment]
I can work on it, kindly assign me this

**Comment by lukes-code** [comment]
> I can work on it, kindly assign me this

Done. Have fun!

**Comment by sheharyarIshfaq** [comment]
I have made changes to the jokes section. But my pull request is not accepted

**Comment by lukes-code** [comment]
Do not need to comment here, I have added comments to the PR
