### ISSUE TITLE
Dynamic contact page

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#67]
At the moment the contact page consists of hard coded cards that have the contributors, it would be awesome if someone could make this dynamic by creating a fetch to github to pull all of the user details dynamically so that we dont have to add them in everytime.

Please ask for this to be assigned before you complete the work.

**Comment by jason1985** [comment]
Hi I would like to work on this if possible.

Thank you.

**Comment by lukes-code** [comment]
> Hi I would like to work on this if possible.
> 
> Thank you.

Be my guest! Enjoy

**Comment by jason1985** [comment]
Great thanks!
