### ISSUE TITLE
Add links to footer

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#69]
The footer looks great, but it would be awesome if you could add hyperlinks to each of the images (e.g. hacktoberfest, intel etc.)
Please make sure that these links open in a new tab and do not affect the styling of the footer. 

*Tip* If you don't know how to make links open in a new tab, Google target blank achor tags *Tip*

Please ask for this case to be assigned before completing the work.

**Comment by amanj752** [comment]
I can do this also assigne to me

**Comment by lukes-code** [comment]
> I can do this also assigne to me

please finish the other assigned log first and then if nobody else has commented, you can do this also

**Comment by GaushJ** [comment]
Hey Can you assign this to me ?

**Comment by sheharyarIshfaq** [comment]
Hi, I can resolve this issue and contribute to this project. Can you assign this to me?

**Comment by lukes-code** [comment]
Project assigned to @GaushJ please can you complete this today, or the issue will get passed along

**Comment by GaushJ** [comment]
> Project assigned to @GaushJ please can you complete this today, or the issue will get passed along
Hey I tried to push my code to a new branch named 'footerhyperlinks' but it is showing some error
 " unable to access 'https://github.com/lukes-code/Hacktoberfest-Spooks.git/': The requested
 URL returned error: 403"
