### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#8]
Need a contact page created, this can be full of fake contact data.
Please try and make it halloween theme (colours etc.)

**Comment by SleepyAryan** [comment]
on it

**Comment by SleepyAryan** [comment]
really sorry..my GitHub desktop was acting up so couldnt push

**Comment by lukes-code** [comment]
> really sorry..my GitHub desktop was acting up so couldnt push

Ok, do you still want to be assigned to this task?

**Comment by SleepyAryan** [comment]
> > really sorry..my GitHub desktop was acting up so couldnt push
> 
> Ok, do you still want to be assigned to this task?

yes

**Comment by theritiktiwari** [comment]
Can I do it ?? If there's a space !!

**Comment by lukes-code** [comment]
> Can I do it ?? If there's a space !!

It has been started, but if you want to you can make it look nicer?

**Comment by theritiktiwari** [comment]
Okay!! Thank you!

**Comment by lukes-code** [comment]
> Okay!! Thank you!

Can you also add the images for each of the current contributors and their usernames instead of the robots?

**Comment by theritiktiwari** [comment]
okay sure!! I'll do that


> 
> Can you also add the images for each of the current contributors and their usernames instead of the robots?

**Comment by theritiktiwari** [comment]
The contributors are added and created a PR.

**Comment by lukes-code** [comment]
All sorted. Added hacktober labels too. Thanks

**Comment by SleepyAryan** [comment]
hey luke..i haven't received a mail from digital ocean yet..is there any issue

**Comment by lukes-code** [comment]
> hey luke..i haven't received a mail from digital ocean yet..is there any issue
> 

The website is quite slow at the moment. When you login to their site what does it say?

**Comment by SleepyAryan** [comment]
> > hey luke..i haven't received a mail from digital ocean yet..is there any issue
> 
> The website is quite slow at the moment. When you login to their site what does it say?

it shows in progress..but 0 completed

**Comment by lukes-code** [comment]
> > > hey luke..i haven't received a mail from digital ocean yet..is there any issue
> > 
> > The website is quite slow at the moment. When you login to their site what does it say?
> 
> it shows in progress..but 0 completed

That is correct! Everyone has to wait 14 days to make sure they are not spam. It will be completed after this time. It's the same for everyone, me too!

**Comment by SleepyAryan** [comment]
> > > > hey luke..i haven't received a mail from digital ocean yet..is there any issue
> > > 
> > > 
> > > The website is quite slow at the moment. When you login to their site what does it say?
> > 
> > 
> > it shows in progress..but 0 completed
> 
> That is correct! Everyone has to wait 14 days to make sure they are not spam. It will be completed after this time. It's the same for everyone, me too!

i see..so it will be done in some days..do you have anything else to work on

**Comment by lukes-code** [comment]
> > > > > hey luke..i haven't received a mail from digital ocean yet..is there any issue
> > > > 
> > > > 
> > > > The website is quite slow at the moment. When you login to their site what does it say?
> > > 
> > > 
> > > it shows in progress..but 0 completed
> > 
> > 
> > That is correct! Everyone has to wait 14 days to make sure they are not spam. It will be completed after this time. It's the same for everyone, me too!
> 
> i see..so it will be done in some days..do you have anything else to work on

Exactly! Don't worry, this is the same for everyone taking part.
I will try to add some more issues in the issues section.
