### ISSUE TITLE
Add a reward modal and some text

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#80]
There is a witch game section. Here you must find the witch on the page (it's in the text of the wrapper) and click it and then you get a "Get Reward" button.

Please add some text to the witch div that says something in small such is "Locate a witch on the page and click it for your reward!"

Please also add a pop up to the page that displays some tasty treats for when the reward button is clicked.

Please comment to be assigned to this issue before completing it.

![image](https://user-images.githubusercontent.com/21207597/135724315-7b79692f-a8d3-4e13-a733-c9199a33ce58.png)

![image](https://user-images.githubusercontent.com/21207597/135724412-e53c7d06-3b54-424d-98f2-065765b1eebc.png)

![image](https://user-images.githubusercontent.com/21207597/135724417-53e18dea-ab7b-4ec4-999e-98bc7c33883d.png)

**Comment by fastboot** [comment]
Can I work on this?

**Comment by lukes-code** [comment]
> Can I work on this?

yes, go ahead! Have fun

**Comment by fastboot** [comment]
Hey @lukes-code,  have a look and let me know if anything else needs to be added or changed. Here's the PR: [Link](https://github.com/lukes-code/Hacktoberfest-Spooks/pull/82)
