### ISSUE TITLE
Add the hacktoberfest footer to all pages

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#89]
Please take the footer from the index.html page and add it to the contact page and the spooky birb page.

**Comment by gokhalevedant06** [comment]
Hello @lukes-code, I would like to fix this, Can you assign this to me?

**Comment by lukes-code** [comment]
> Hello @lukes-code, I would like to fix this, Can you assign this to me?

Sure, have fun!
