### ISSUE TITLE
Fix the nav on game page

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#90]
Please fix the navbar on the spooky birb game page so that it works like the index.html page

**Comment by Anas-hameed** [comment]
I would like to work on this. Can you assign this to me?

**Comment by lukes-code** [comment]
> I would like to work on this. Can you assign this to me?

Sure, have fun!

**Comment by harshrawat20** [comment]
I would like to work on this can you assign it too me?

**Comment by lukes-code** [comment]
> I would like to work on this can you assign it too me?

Only one person for this job sorry.

**Comment by harshrawat20** [comment]
okay by the way few other issues are already resolved then why they are still open?

**Comment by lukes-code** [comment]
> okay by the way few other issues are already resolved then why they are still open?

Allow me to worry about that
