### ISSUE TITLE
Change the wrapper text and placement

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#91]
Please change the text on index.html in the header to something more interesting and halloween.
Also, move the text and button so that it is on the right side and not the left.

**Comment by pccoder-2000** [comment]
I would like to work on this issue ;)

**Comment by lukes-code** [comment]
> I would like to work on this issue ;)

Sure, enjoy

**Comment by aashi-mishra** [comment]
i would like to solve this issue.

**Comment by lukes-code** [comment]
> i would like to solve this issue.

This has already been assigned
