### ISSUE TITLE
Fix the witch game responsive

### ISSUE THREAD

**Issue by lukes-code** [lukes-code/Hacktoberfest-Spooks#92]
Please make the "find the witch" section on index.html responsive for mobile.

**Comment by shashank1503-cipher** [comment]
Hey i would like to work on this

**Comment by Anas-hameed** [comment]
Hello, Can I work on this?

**Comment by lukes-code** [comment]
Assigned to @shashank1503-cipher

**Comment by RahulRudra81** [comment]
hey you told me to work on this can you assign it to me

**Comment by lukes-code** [comment]
> hey you told me to work on this can you assign it to me 
> 

I told you to comment here, took too long and someone else is now assigned

**Comment by shashank1503-cipher** [comment]
Hey I have made a PR for this issue
Please Review.
